### PR TITLE
Bump qc-d dependency

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
Update the dependency on quickcheck-dynamic to point to the latest version.

### CODE REVIEW

**Comment by MaximilianAlgehed** [comment]
@berewt any clue what's up with ci here?

**Review by sjoerdvisscher — APPROVED** [review]

**Comment by sjoerdvisscher** [comment]
Sorry, ignore that :)

**Comment by zeme-wana** [comment]
This PR is failing because there are no `hydraJobs` outputs in the flake. 
This is expected: we've added this repo to CI but not updated the flake yet.
I suggest we merge this PR first (https://github.com/input-output-hk/quickcheck-contractmodel/pull/21)
And the we can deal with this one

**Comment by MaximilianAlgehed** [comment]
@zeme-wana that sounds good. Just let me know when the other PR is ready and I expect we can merge it right away.

**Comment by zeme-wana** [comment]
https://github.com/input-output-hk/quickcheck-contractmodel/pull/22 has been merged. We can now merge this.

Remember that the formatters are not enabled yet.
You will want to open a new PR, set `cabal-fmt.enable = true; fourmolu.enable = true;` in `./nix/formatters.nix` then run `pre-commit run --all-files`

**Review by sjoerdvisscher — APPROVED** [review]

**Comment by MaximilianAlgehed** [comment]
@zeme-wana this appears to be stuck on flaky CI.

**Comment by zeme-wana** [comment]
I restarted the false-negative build failures on Hydra and now it's all good.

**Pull request merged**
