### PR TITLE
IOGX Integration

### PR DESCRIPTION
**Pull request by zeme-wana**
As part of the ongoing effort to build a Developer Platform for IOG, the smart-contracts-dev-empowerment team is releasing [IOGX - a Flake Template for Haskell Projects at IOG](https://github.com/input-output-hk/iogx)

_The vision of IOGX is to provide a JSON-like, declarative interface to Nix, so that developers unfamiliar with the language may independently maintain and add to the Nix sources with minimum effort and maximum pleasure._

The goal is to integrate with all Smart Contracts repositories, and maybe more.

As developers nothing changes for you: you will enter nix develop and you will get into a new shell.

There might be some rough edges but we will be prompt to smooth them.

### CODE REVIEW

**Comment by zeme-wana** [comment]
Waiting to integrate this into Hydra CI before merging

**Comment by zeme-wana** [comment]
@MaximilianAlgehed I'm merging this now, but it doesn't include formatting changed from `cabal-fmt` and `fourmolu`
Like we did for qc-dynamic, if you want to enable the formatters, you'll have to open a new PR, set `{cabal-fmt,fourmolu}.enable = true;` in `./nix/pre-commit-check.nix`, run `pre-commit run --all-files` and commit the changes

**Comment by MaximilianAlgehed** [comment]
@zeme-wana what's the status on this? I can fiddle around with format later if necessary.

**Comment by zeme-wana** [comment]
CI is not responding: re-opening here https://github.com/input-output-hk/quickcheck-contractmodel/pull/22

**Pull request closed without merging**
