### PR TITLE
Upgrade cardano-node dependency

### PR DESCRIPTION
**Pull request by sjoerdvisscher**
Update to cardano-node 8.2 and ghc 9.2.8.

### CODE REVIEW

**Comment by sjoerdvisscher** [comment]
@MaximilianAlgehed No idea what's going on with the aarch64-darwin build!

**Comment by MaximilianAlgehed** [comment]
@zeme-wana any clue what's up here? Is this just a silly thing related to the latest github meltdown?

**Comment by MaximilianAlgehed** [comment]
@sjoerdvisscher if you force push this branch that might re-trigger the build.

**Comment by zeme-wana** [comment]
It's good now

**Comment by zeme-wana** [comment]
It's good now @sjoerdvisscher

**Comment by sjoerdvisscher** [comment]
That's a relief! But I'm getting some errors while running tests in plutus-apps, so let's not merge this until I know if that's a bug here or in plutus-apps.

**Review by zeme-wana — APPROVED** [review]

**Comment by zeme-wana** [comment]
Gonna merge this

**Pull request merged**
